export default function AIConsentModal({ onAccept, onDecline, loading }) {
  return (
    <div className="consent-card">
      <div className="consent-card-header">
        <span className="consent-card-icon">◈</span>
        <h3>Before you continue</h3>
      </div>
      <p className="consent-card-intro">
        Six Eyes uses the Claude AI API to generate responses. Here is exactly what that means for your data:
      </p>
      <ul className="consent-list">
        <li>
          <span className="consent-check" style={{ color: 'var(--color-safe)' }}>✓</span>
          <span>Your prompt text and a summary of your security score are sent to Anthropic's API to generate a response</span>
        </li>
        <li>
          <span className="consent-check" style={{ color: 'var(--color-danger)' }}>✗</span>
          <span>Your passwords, email address, and breach results are <strong>never</strong> included</span>
        </li>
        <li>
          <span className="consent-check" style={{ color: 'var(--color-safe)' }}>✓</span>
          <span>Responses are generated by <strong>Claude Haiku</strong> — a fast, privacy-conscious model</span>
        </li>
        <li>
          <span className="consent-check" style={{ color: 'var(--color-safe)' }}>✓</span>
          <span>Every AI call is logged as a hash in your audit trail — you can review or withdraw consent at any time from the Privacy Dashboard</span>
        </li>
      </ul>
      <p className="consent-card-footer muted">
        By continuing, you agree that prompt text may be processed by Anthropic in accordance with their{' '}
        <a href="https://www.anthropic.com/privacy" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--color-blue)' }}>
          privacy policy
        </a>.
      </p>
      <div className="consent-actions">
        <button className="btn-primary" onClick={onAccept} disabled={loading}>
          {loading ? 'Saving…' : 'I understand, continue'}
        </button>
        <button className="btn-ghost" onClick={onDecline}>
          No thanks
        </button>
      </div>
    </div>
  );
}
