export default function AIDisclosure({ model = 'Anthropic Haiku' }) {
  return (
    <p className="ai-disclosure">
      AI-generated by {model} · May be inaccurate · Not professional security advice
    </p>
  );
}
